package com.nchu.mapper;

import com.nchu.domain.DO.Question;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */

    int updateGoodOrBad(@Param("questionId") Long questionId,@Param("key") Integer key,@Param("goodNum") Long goodNum,@Param("badNum") Long badNum);
    int updateCream(Question record);
    int updateVisit(Question record);

    List<Question>  selectQuestionList(@Param("courseId") Long courseId,@Param("level") Long level,@Param("currentPage")  Integer currentPage,@Param("pageSize") Integer pageSize);
    Integer selectCountQuestion(@Param("courseId") Long courseId,@Param("level") Long level);

    List<Question>  selectQuestionListByUID(@Param("UID") Long UID, @Param("currentPage") Integer currentPage,@Param("pageSize") Integer pageSize);
    Integer selectCountQuestionByUID(@Param("UID") Long UID);


    Integer selectCountQuestionForKey(@Param("key") String key);


    List<Question> questionSearcher(@Param("key") String key,@Param("currentPage") Integer currentPage ,@Param("pageSize") Integer pageSize);


    int deleteByPrimaryKey(Long questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    int insert(Question record);
    int insertSelective(Question record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */

    Question selectByPrimaryKey(Long questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    List<Question> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */

    int updateByPrimaryKey(Question record);

    List<Question> isCreamQuetion(@Param("currentPage")  Integer currentPage,@Param("pageSize") Integer pageSize);
    int isCreamQuetionCount();

    List<Question> newQuetionAll(@Param("currentPage")  Integer currentPage,@Param("pageSize") Integer pageSize);
    int newQuetionAllCount();

    List<Question> isCreamQuetionbyCourseId(@Param("courseId") Long courseId,@Param("currentPage")  Integer currentPage,@Param("pageSize") Integer pageSize);
    int isCreamQuetionCountbyCourseId(@Param("courseId") Long courseId);

}