package com.nchu.domain.DO;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbggenerated
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.bad_num
     *
     * @mbggenerated
     */
    private Long badNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.course_id
     *
     * @mbggenerated
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.good_num
     *
     * @mbggenerated
     */
    private Long goodNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.person_id
     *
     * @mbggenerated
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.person_name
     *
     * @mbggenerated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.question_id
     *
     * @mbggenerated
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbggenerated
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.bad_num
     *
     * @return the value of comment.bad_num
     *
     * @mbggenerated
     */
    public Long getBadNum() {
        return badNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.bad_num
     *
     * @param badNum the value for comment.bad_num
     *
     * @mbggenerated
     */
    public void setBadNum(Long badNum) {
        this.badNum = badNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.course_id
     *
     * @return the value of comment.course_id
     *
     * @mbggenerated
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.course_id
     *
     * @param courseId the value for comment.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.good_num
     *
     * @return the value of comment.good_num
     *
     * @mbggenerated
     */
    public Long getGoodNum() {
        return goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.good_num
     *
     * @param goodNum the value for comment.good_num
     *
     * @mbggenerated
     */
    public void setGoodNum(Long goodNum) {
        this.goodNum = goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.person_id
     *
     * @return the value of comment.person_id
     *
     * @mbggenerated
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.person_id
     *
     * @param personId the value for comment.person_id
     *
     * @mbggenerated
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.person_name
     *
     * @return the value of comment.person_name
     *
     * @mbggenerated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.person_name
     *
     * @param personName the value for comment.person_name
     *
     * @mbggenerated
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.question_id
     *
     * @return the value of comment.question_id
     *
     * @mbggenerated
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.question_id
     *
     * @param questionId the value for comment.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.time
     *
     * @return the value of comment.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.time
     *
     * @param time the value for comment.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentId=").append(commentId);
        sb.append(", badNum=").append(badNum);
        sb.append(", content=").append(content);
        sb.append(", courseId=").append(courseId);
        sb.append(", goodNum=").append(goodNum);
        sb.append(", personId=").append(personId);
        sb.append(", personName=").append(personName);
        sb.append(", questionId=").append(questionId);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}